POS.UI/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using POS.DAL.Repository.IRpository;
using POS.Models.AppVM;
using POS.Models.EntityModel;

namespace POS.UI.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHost;
        public SuppliersController(IUnitOfWork unitOfWork, IWebHostEnvironment webHost)
        {
            _unitOfWork = unitOfWork;
            this._webHost = webHost;
        }
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Upsert(int? id)
        {
            List<Supplier> supplierList = new List<Supplier>();
            supplierList = _unitOfWork.Supplier.GetAll().ToList();

            SupplierVM supplierVM = new()
            {
                Supplier = new(),

            };
            if (id == null || id == 0)
            {

                return View(supplierVM);
            }
            else
            {
                supplierVM.Supplier = _unitOfWork.Supplier.GetFirstOrDefault(x => x.Id == id);
                return View(supplierVM);
            }



         
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Upsert(SupplierVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Supplier.Id == 0)
                    {
                        _unitOfWork.Supplier.Add(model.Supplier);
                    }
                    else
                    {
                        _unitOfWork.Supplier.Update(model.Supplier);
                    }
                    _unitOfWork.Save();
                    TempData["success"] = "Supplier Created Succesfully!";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    var err = ex.Message;
                }
            }
            return View(model);
        }



        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var supplierList = _unitOfWork.Supplier.GetAll();

            return Json(new { data = supplierList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            var supplier = _unitOfWork.Supplier.GetFirstOrDefault(f => f.Id == id);
            if (supplier == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }

            _unitOfWork.Supplier.Remove(supplier);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted Successfully!" });
        }
        #endregion


    }
}

POS.UI/Views/Suppliers/Index.cshtml
@using POS.Models.EntityModel

@model IEnumerable<Supplier>
@{
    ViewData["Title"] = "Index";
}

<div class="py-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-dark">Supplier List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Suppliers" asp-action="Upsert" class="btn-info btn btn-sm">
                <i class="fa-solid fa-square-plus"></i> &nbsp; Create New Supplier
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card card-body mb-2">
            <form action="">
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <input type="text" name="name" class="form-control" placeholder="Name" value="">
                    </div>

                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" name="number" placeholder="Mobile Number" value="">
                    </div>




                </div>
                <div class="form-row mt-2">
                    <div class="form-group float-right">
                        <button class="btn btn-success btn-sm" type="submit">
                            <i class="fa fa-sliders"></i>
                            Filter
                        </button>
                        <a href="https://pos.softghor.com/back/product" class="btn btn-info btn-sm">Reset</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<table class="table table-bordered table-striped table-sm" style="width:100%" id="SupplierTbl">
    <thead class="bg-info">
        <tr>
          
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Receivable</th>
            <th>Paid</th>
            <th>Purchase Due</th>
            <th>Wallet Balance</th>
            <th>Total Due</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
    </tbody>


</table>

@section Scripts{
    <script src="~/js/Supplier/supplier.js"> </script>

}

POS.UI/Views/Suppliers/Upsert.cshtml
@model SupplierVM
@{
    ViewData["Title"] = "Create";
}

<div p-3">
    <div class="row">
        <div class="col-md-12 ">

            <form class="" asp-action="Upsert" method="post">
                <div class="border mt-4 p-3">
                    <div class="row pb-2">
                        <h2 class="text-dark">Create Supplier</h2>
                        <hr />

                    </div>

                    <input hidden asp-for="Supplier.Id" />
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="Supplier.SupplierName"></label>
                                <input asp-for="Supplier.SupplierName" class="form-control" />
                                <span asp-validation-for="Supplier.SupplierName" class="text-danger"></span>
                            </div>
                        </div>




                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="Supplier.Email"></label>
                                <input asp-for="Supplier.Email" class="form-control" />
                                <span asp-validation-for="Supplier.Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="Supplier.Address"></label>
                                <textarea asp-for="Supplier.Address" class="form-control"></textarea>
                                <span asp-validation-for="Supplier.Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="Supplier.Phone"></label>
                                <input asp-for="Supplier.Phone" class="form-control" />
                                <span asp-validation-for="Supplier.Phone" class="text-danger"></span>
                            </div>
                        </div>
                        @if (Model.Supplier.Id==0)
                        {
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label asp-for="Supplier.OpeningReceivable"></label>
                                    <input asp-for="Supplier.OpeningReceivable" class="form-control" />
                                    <span asp-validation-for="Supplier.OpeningReceivable" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label asp-for="Supplier.OpeningPayable"></label>
                                    <input asp-for="Supplier.OpeningPayable" class="form-control" />
                                    <span asp-validation-for="Supplier.OpeningPayable" class="text-danger"></span>
                                </div>
                            </div>
                        }
                      
                    </div>

                    <div class="mb-2 text-center unit-count" style="display:none">
                        <label for="">1= </label>

                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-info" style="width:150px">Submit</button>
                        <a asp-controller="Suppliers" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts
    {

    @{
        <partial name="_ValidationScriptsPartial.cshtml" />

    }
    <script src="~/js/Supplier/supplier.js"></script>
}