POS.UI/Controllers/DamagesController.cs
using Microsoft.AspNetCore.Mvc;
using POS.DAL.Repository.IRpository;
using POS.Models.AppVM;
using POS.Models.EntityModel;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace POS.UI.Controllers
{
    public class DamagesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;


        public DamagesController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            ViewBag.ProductList = new SelectList(_unitOfWork.Product.GetAll(), "Id", "Name");
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            List<Product> productList = new List<Product>();
            productList = _unitOfWork.Product.GetAll().ToList();
            foreach (Product product in productList)
            {
                product.Unit = _unitOfWork.Unit.GetFirstOrDefault(f => f.Id == product.UnitId);
            }
            DamageVM damageVM = new()
            {
                Damage = new(),
                ProductList = productList.Select(i => new SelectListItem
                {
                    Text = i.Name + " - " + "Stock: " + i.Stock.ToString() + i.Unit.Name,
                    Value = i.Id.ToString()
                }),
            };
            if (id == null || id == 0)
            {
                ViewBag.ProductList = new SelectList(_unitOfWork.Product.GetAll(), "Id", "Name");
                return View(damageVM);
            }
            else
            {
                damageVM.Damage = _unitOfWork.Damage.GetFirstOrDefault(x => x.Id == id);
                return View(damageVM);
            }



            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Upsert(DamageVM obj)
        {
            if (ModelState.IsValid)
            {
                var model = new Damage();
                model = obj.Damage;
                //Create Product
                if (obj.Damage.Id == 0)
                {

                    _unitOfWork.Damage.Add(model);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }

                //Update Products
                else
                {
                    _unitOfWork.Damage.Update(model);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }

            }
            return View(obj);
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var damageList = _unitOfWork.Damage.GetAll();

            return Json(new { data = damageList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            var damage = _unitOfWork.Damage.GetFirstOrDefault(f => f.Id == id);
            if (damage == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }

            _unitOfWork.Damage.Remove(damage);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted Successfully!" });
        }
        #endregion
    }
}

POS.UI/Views/Damages/Index.cshtml
@using POS.Models.EntityModel

@model IEnumerable<Damage>
@{
    ViewData["Title"] = "Index";
}

<div class=" py-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-dark">Damage List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Damages" asp-action="Upsert" class="btn-info btn btn-sm">
                <i class="fa-solid fa-square-plus"></i> &nbsp; Create New Damage
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card card-body mb-2">
            <form action="">
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <select class="form-control" placeholder="Name" asp-items=" ViewBag.ProductList">
                            <option value="">Select Product</option>
                        </select>
                    </div>

                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" name="number"  value="">
                    </div>




                </div>
                <div class="form-row mt-2">
                    <div class="form-group float-right">
                        <button class="btn btn-success btn-sm" type="submit">
                            <i class="fa fa-sliders"></i>
                            Filter
                        </button>
                        <a href="https://pos.softghor.com/back/product" class="btn btn-info btn-sm">Reset</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<table class="table table-bordered table-striped table-sm" style="width:100%" id="DamageTbl">
    <thead class="bg-info">
        <tr>

            <th>Id</th>
            <th>Date</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Note</th>
            <th>Action</th>


        </tr>
    </thead>
    <tbody>
    </tbody>


</table>

@section Scripts{
    <script src="~/js/Damage/damage.js"> </script>

}

POS.UI/Views/Damages/Upsert.cshtml
@model DamageVM

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-dark">Create Damage</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Damage.ProductId"></label>
			<select asp-for="Damage.ProductId" class="form-control basic-select2" asp-items="@Model.ProductList" id="ProductList">
				<option value="">Select Product</option>
			</select>
			<span asp-validation-for="Damage.ProductId" class="text-danger"></span>
		</div>
			<div class="mb-3 damage-qty">
			<label >pc:</label>
			<input class="form-control" type="number" id="qty" />
			
		</div>
		<div class="mb-3 " >
			<label >Date </label>
			<input  type="text" class="form-control" id="getCurrentDate" >
			
			<span asp-validation-for="Damage.CreatedDate" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Damage.Note"></label>
			<textarea asp-for="Damage.Note" class="form-control" ></textarea>
			<span asp-validation-for="Damage.Note" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-info" style="width:150px">Create</button>
		<a asp-controller="Damages" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
	<script src="~/js/Damage/damage.js"> </script>
}